<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart_full</name>
   <tag></tag>
   <elementGuidId>58044025-0b39-4627-9687-e26e316ad1c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabletHeader']/div[4]/nav/med-navbar/section/ul/li[6]/div/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabletHeader&quot;)/div[@class=&quot;row nav-wrapper&quot;]/nav[@class=&quot;col-sm-12&quot;]/med-navbar[@class=&quot;ng-tns-c0-1&quot;]/section[1]/ul[@class=&quot;nav-menu&quot;]/li[@class=&quot;nav-menu-list cart hidden-xs&quot;]/div[1]/a[@class=&quot;icon shopping-cart&quot;]/span[@class=&quot;full&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabletHeader']/div[4]/nav/med-navbar/section/ul/li[6]/div/a/span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
   </webElementXpaths>
</WebElementEntity>
