<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Packing Slip_checkbox-icon large</name>
   <tag></tag>
   <elementGuidId>0f5562fd-a1bd-42af-afd0-c06db87d8e92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='shoppingCartContainer']/section/med-shopping-cart-details/div/div[3]/div/div/span/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon large</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>selectAll</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCartContainer&quot;)/section[@class=&quot;row&quot;]/med-shopping-cart-details[1]/div[@class=&quot;shopping-cart-wrapper col-xs-12&quot;]/div[@class=&quot;cart-ctas-container&quot;]/div[@class=&quot;cart-ctas clearfix&quot;]/div[@class=&quot;cart-ctas-left-col&quot;]/span[@class=&quot;checkbox-container select-all&quot;]/label[@class=&quot;checkbox-label&quot;]/span[@class=&quot;checkbox-icon large&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='shoppingCartContainer']/section/med-shopping-cart-details/div/div[3]/div/div/span/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
